plugins:
- jekyll-remote-theme
- jekyll-relative-links
relative_links:
  enabled: true
  collections: true
title: RETROGENius
url: "https://retrogeniuspro.github.io"
baseurl: "/site"
permalink: /:year/:month/:day/:title/
remote_theme: pages-themes/hacker@v0.2.0