title: RETROGENius
description: Where yesterday's tech meets tomorrow's innovation
baseurl: "/site"
url: "https://retrogeniuspro.github.io"
permalink: /:year/:month/:day/:title/
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme