title: [RETROGENius]
description: [Where yesterday's tech meets tomorrow's innovation]
url: "https://retrogeniuspro.github.io"
permalink: /site/:year/:month/:day/:title/
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme